# fly.toml app configuration file generated for price-history-chainlink on 2026-01-11

app = "price-history-chainlink"
primary_region = "sjc"

[build]

[env]
  POOL_SIZE = "10"

[deploy]
  release_command = "/app/bin/price_history eval PriceHistory.Release.migrate"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
